### ISSUE TITLE
cargo installed svd2rust not working

### ISSUE THREAD

**Issue by bittsitt** [rust-embedded/svd2rust#869]
Cargo installed version of svd2rust fails on both mac, linux and windows (wsl). 

If I clone the repo, build and run, it works just fine. 

cargo install svd2rust
```
$ svd2rust -i STM32F030.svd -o tmp
[INFO  svd2rust] Parsing device from SVD file
[INFO  svd2rust] Rendering device
thread 'main' panicked at /home/bs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.87/src/lib.rs:847:13:
unsupported proc macro punctuation character '{'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
With backtrace

```
$ RUST_BACKTRACE=full svd2rust -i STM32F030.svd -o tmp
[INFO  svd2rust] Parsing device from SVD file
[INFO  svd2rust] Rendering device
thread 'main' panicked at /home/bs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.87/src/lib.rs:847:13:
unsupported proc macro punctuation character '{'
stack backtrace:
   0:     0x555717ec29ba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hc5cfde4eb972914c
   1:     0x555717ee70c3 - core::fmt::write::he0971e8e7c5c04ea
   2:     0x555717ebfa93 - std::io::Write::write_fmt::h240c15cbb6da5e6b
   3:     0x555717ec2802 - std::sys::backtrace::BacktraceLock::print::he74b67f64941b60a
   4:     0x555717ec37ac - std::panicking::default_hook::{{closure}}::h21f7bf3c0f7926bf
   5:     0x555717ec35f2 - std::panicking::default_hook::hd27e0ee7bd40fd55
   6:     0x555717ec3de7 - std::panicking::rust_panic_with_hook::hc78f159b6cd62717
   7:     0x555717ec3c7a - std::panicking::begin_panic_handler::{{closure}}::h429b75e7cc3fa34f
   8:     0x555717ec2e99 - std::sys::backtrace::__rust_end_short_backtrace::h770cd9fe71a3f33d
   9:     0x555717ec390c - rust_begin_unwind
  10:     0x555717ee51a0 - core::panicking::panic_fmt::h948b536db9ba3b6a
  11:     0x555717e8f817 - proc_macro2::Punct::new::h1af609d07979782a
  12:     0x555717bbe89a - svd2rust::generate::register::render_register_mod::hf710f6e24abd5c4d
  13:     0x555717bbcdb6 - svd2rust::generate::register::render::h6519410c87cc9295
  14:     0x555717bb176c - svd2rust::generate::peripheral::render_ercs::h5a48b400acd6a4ec
  15:     0x555717ba25e3 - svd2rust::generate::peripheral::render::h6c8da1eeb993c84e
  16:     0x555717c0bc57 - svd2rust::generate::device::render::h9be863d062b94f01
  17:     0x555717a791c9 - svd2rust::run::h106e61d7aad24c8f
  18:     0x555717a7bb1d - svd2rust::main::hc8fbfced843d90a3
  19:     0x555717a90c53 - std::sys::backtrace::__rust_begin_short_backtrace::h37dfef09e52dfef3
  20:     0x555717a8c7a9 - std::rt::lang_start::{{closure}}::hde377824c74bd85d
  21:     0x555717eb913e - std::rt::lang_start_internal::h55dd5ea43508de18
  22:     0x555717a7bc45 - main
  23:     0x7f9bdf8d7d90 - <unknown>
  24:     0x7f9bdf8d7e40 - __libc_start_main
  25:     0x555717a62515 - _start
  26:                0x0 - <unknown>

```

**Comment by Emilgardis** [comment]
install with `--locked` for now

duplicates #863
